[package]
name = "esp32c3-rust-mqtt"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
embassy-executor = { version = "0.6", features = [ "integrated-timers", "task-arena-size-20480" ] }
embassy-net = { version = "0.4", features = ["tcp", "udp", "dhcpv4", "medium-ethernet", "proto-ipv6", "log", "dns"] }
embassy-time       = { version = "0.3" }
embedded-io-async = "0.6"
esp-backtrace = { version = "0.14", features = ["esp32c3", "println", "panic-handler", "exception-handler" ] }
esp-hal = { version = "0.21", features = ["esp32c3"] }
esp-hal-embassy = { version = "0.4", features = ["esp32c3"] }
esp-println = { version = "0.12", features = ["esp32c3","log"] }
esp-wifi = { version = "0.10", features = ["esp32c3", "async", "embassy-net", "wifi", "ipv6"] }
heapless = "0.8"
static_cell = { version = "2", features = ["nightly"] }

rust-mqtt = { version = "0.3", default-features = false }
rand_core = "0.6"
embassy-sync = { version = "0.6" }
esp-alloc = "0.5.0"
thiserror = { version = "2.0.3", default-features = false }

[profile.dev.package.esp-wifi]
opt-level = 3

[profile.dev]
lto = "off"

[profile.release]
lto = "off"
