[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "force-frame-pointers",
    "-C", "link-arg=-Tdefmt.x",
    "-C", "debuginfo=2",
    "-C", "strip=none"
]

[build]
target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = [ "core" ]
